<?php
/*$popular_source = file_get_contents('http://api.themoviedb.org/3/movie/popular?api_key=51b3407616db4fe78f36b0c9e7ea0366&language=fr');
$popular_data = json_decode($popular_source, true);

$upcoming_source = file_get_contents('http://api.themoviedb.org/3/movie/upcoming?api_key=51b3407616db4fe78f36b0c9e7ea0366&language=fr');
$upcomingtop_rated_data = json_decode($upcoming_source, true);*/

  function api_help($path, $arg) {
    switch ($path) {
      case 'admin/help#api':
      return '<p>'.t('Go to Configure -> api and select the category of films that you want to add/update').'</p>';
      break;
    }
  }

function add_update_top_rated(){
      $top_rated_source = file_get_contents('http://api.themoviedb.org/3/movie/top_rated?api_key=51b3407616db4fe78f36b0c9e7ea0366&language=fr');
      $top_rated_data = json_decode($top_rated_source, true);
      $tabsize = count($top_rated_data['results']);
      //var_dump($json_data['results']);
      //echo $tabsize;

     for ($i = 0; $i<2; $i++)
      {
        $title = $top_rated_data['results'][$i]['title'];
        $cover = $top_rated_data['results'][$i]['poster_path'];
        $overview = $top_rated_data['results'][$i]['overview'];
        $date = $top_rated_data['results'][$i]['release_date'];

        // Create node
        $node = new stdClass();
        // Set some default values
        $node->type = 'movie';
        node_object_prepare($node);
        // Add title
        $node->title = $title;
        // Add infos
        $node->field_movie_synopsis[LANGUAGE_NONE][0]['value'] = $overview;
        $node->field_movie_date[LANGUAGE_NONE][0]['value'] = $date;
        $node->field_movie_type[LANGUAGE_NONE][0]['tid'] = 18;
        //$node->field_movie_director[LANGUAGE_NONE][0]['tid'] = 18;
        // Add image
        $image_url = 'http://image.tmdb.org/t/p/w1000' . $cover;
        $file = system_retrieve_file($image_url, file_default_scheme() . '://cover_' . basename($title).'.jpg', TRUE);
        $node->field_movie_cover[LANGUAGE_NONE][0] = (array)$file;

        // // Save the node
        node_save($node);
        $node->field_movie_synopsis[LANGUAGE_NONE][0]['value'] = $overview;
      }
}

function api_menu() {
  $items = array();
  $items['admin/config/content/api'] = array(
    'title' => 'api',
    'description' => t("Add and update movie's informations on your website"),
    'page callback' => 'api_config_page',
    'page arguments' => array('api'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function api_config_page(){
    $build = array();

    $build['form_one'] = drupal_get_form('top_rated_form');
    $build['form_two'] = drupal_get_form('upcoming_form');
    $build['form_three'] = drupal_get_form('popular_form');

    //return '<p>'.t('Create and update movies content').'</p>';
    return $build;
}

function top_rated_form($form, &$form_state){
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Top rated'),
    '#weight' => 1,
  );
  return $form;
}

function upcoming_form($form, &$form_state){
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Upcoming'),
    '#weight' => 1,
  );
  return $form;
}

function popular_form($form, &$form_state){
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Popular'),
    '#weight' => 1,
  );
  return $form;
}

function top_rated_form_submit($form, &$form_state) {
  add_update_top_rated();
  drupal_set_message(t('The top rated films were correctly added or update'));
}

// ---------- get term id -------- //
    /*
    $terms="Les mieux notés";

    $terms = taxonomy_get_term_by_name("Les mieux notés");
    $all_term = current($terms);
    $terms = taxonomy_get_term_by_name("Les mieux notés");
    $words_term = current($terms);
    $all_tid = $all_term->tid;
    $words_tid = $words_term->tid;
    echo $words_tid;
    */



  // ---------- FIND ITEM ----------
// Make API Request to get the result the result of the research, display the results


/*  function api_node_insert($node) {
    db_insert('movie')
      ->fields(array(
        'lol' => $node->field_movie_synopsis,
        'lol' => $node->field_movie_type,
      ))
      ->execute();
  } */ 


/*$GLOBALS['apikey'] = '** API KEY **';

function add_item_help($path, $arg)
{
    switch ($path) {
        // Main module help for the block module
        case 'admin/help#add_item':
            return '<p>' . t('Hello') . '</p>';
    }
}

function add_item_permission()
{
    return array(
        'administer add item module' => array(
            'title' => t('Administer the add item module'),
            'description' => t('Perform administration tasks for this module.'),
        ),
    );
}

function add_item_menu()
{
    $items['search_item'] = array(
        'title' => 'Ajouter un film',
        'page callback' => 'search_item',
        'access callback' => TRUE,
    );
    $items['find_item'] = array(
        'page callback' => 'find_item',
        'access callback' => TRUE,
    );
    $items['add_item'] = array(
        'page callback' => 'add_item',
        'access callback' => TRUE,
    );
    return $items;
}


// ---------- SEARCH ITEM ----------
// Get the movie name
function search_item()
{
    return drupal_get_form('form_add_item');
}
function form_add_item($form, &$form_state)
{
    $form['movie_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Movie Title'),
        '#description' => t('Enter the movie title.'),
    );
    $form['search'] = array(
        '#type' => 'submit',
        '#value' => t('Search'),
    );
    return $form;
}
function form_add_item_validate($form, &$form_state){
  if(empty($form_state['values']['movie_title'])) {
    form_set_error('movie_title', t('Field must be register!'));
  }
}
function form_add_item_submit($form, &$form_state){
    $movieName = $form_state['values']['movie_title'];
    $form_state['redirect'] = array( 'find_item', array( 'query' => array( 'query' => $movieName, ) ),);
}


// ---------- FIND ITEM ----------
// Make API Request to get the result the result of the research, display the results
function find_item()
{
    $movieName = $_GET['query'];
    return searchMovie($movieName);
}

// ---------- FIND ITEM ----------
// Make API Request to get the result the result of the research, display the results

function add_item()
{   
    $movieID = $_GET['id'];
    $infos = getMovie($movieID);
    // Create node
    $node = new stdClass();
    // Set some default values
    $node->type = 'movies';
    node_object_prepare($node);
    // Add title
    $node->title = $infos->title;
    // Add infos
    $node->body[LANGUAGE_NONE][0]['value'] = $infos->overview;
    $node->body[LANGUAGE_NONE][0]['format'] = 'full_html';
    // Add image
    $image_url = 'http://image.tmdb.org/t/p/w1000' . $infos->poster_path;
    $file = system_retrieve_file($image_url, file_default_scheme() . '://movie_poster' . basename($infos->title), TRUE);
    $node->field_movie_pochette[LANGUAGE_NONE][0] = (array)$file;
    // // Save the node
    node_save($node);
    drupal_goto('<front>');
}

// --------- FONCTIONS API --------- //
// Search movies by name
// IN --> Movie Name // OUT --> List of movies
function searchMovie($movieName)
{
    $movienameURL = urlencode($movieName);
    $url = "http://api.themoviedb.org/3/search/movie?query=". $movienameURL ."&api_key=". $GLOBALS['apikey'] ."&language=fr";
    $options = array(
      'method' => 'GET',
    );
    $request = drupal_http_request($url, $options);
    $json = json_decode($request->data);
    $results = $json->results;
    $ret = '';
    foreach($results as $movie) {
        $ret .= '<div class="add_item-movie"><div class="add_item-img"><img src="http://image.tmdb.org/t/p/w370' . $movie->poster_path . '"></div><div class="add_item-infos"><h1>' . $movie->title . '</h1><p>' . $movie->overview .' </p></div>'. l(t("Add movie"), url("add_item"), array('query' => array('id' => $movie->id ))) .'</div>';
    }
    return $ret;
}
function getMovie($movieID)
{
    $movieidURL = urlencode($movieID);
    $url = "http://api.themoviedb.org/3/movie/". $movieidURL ."?api_key=". $GLOBALS['apikey'] ."&language=fr";
    $options = array(
      'method' => 'GET',
    );
    $request = drupal_http_request($url, $options);
    $infos = json_decode($request->data);
    return $infos;
}*/